#!/usr/bin/env python3
"""
build_dict.py - Compile a bilingual CSV into a C header for the translate module.

Usage:
    python3 tools/build_dict.py dict/sample.csv modules/translate/dict_data.h

Input CSV format (UTF-8, no trailing spaces):
    en,zh
    hello,你好
    world,世界
    ...

The first row is treated as a header and skipped.  Lines starting with '#'
are comments.  Whitespace around keys/values is stripped.

Output:
    A self-contained dict_data.h with two sorted, static const tables:
      - tr_en2zh  (English key  -> Chinese value, case-insensitive sorted)
      - tr_zh2en  (Chinese key -> English value, UTF-8 byte-order sorted)
    Binary search in translate.c relies on this sort order.
"""

import csv
import sys
import os


def c_escape(s: str) -> str:
    """Escape a string for use inside a C double-quoted literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    if len(sys.argv) != 3:
        print("Usage: build_dict.py <input.csv> <output.h>", file=sys.stderr)
        sys.exit(1)

    csv_path = sys.argv[1]
    out_path = sys.argv[2]

    pairs: list[tuple[str, str]] = []
    with open(csv_path, "r", encoding="utf-8") as f:
        reader = csv.reader(f)
        header_skipped = False
        for row in reader:
            if not row or len(row) < 2:
                continue
            k = row[0].strip()
            v = row[1].strip()
            if not k or not v or k.startswith("#"):
                continue
            if not header_skipped:
                header_skipped = True
                continue
            pairs.append((k, v))

    # Build en->zh (deduplicate by English key, case-insensitive)
    seen_en: set[str] = set()
    en2zh: list[tuple[str, str]] = []
    for k, v in pairs:
        key_lower = k.lower()
        if key_lower not in seen_en:
            seen_en.add(key_lower)
            en2zh.append((k, v))
    en2zh.sort(key=lambda x: x[0].lower())

    # Build zh->en (deduplicate by Chinese key)
    seen_zh: set[str] = set()
    zh2en: list[tuple[str, str]] = []
    for k, v in pairs:
        if v not in seen_zh:
            seen_zh.add(v)
            zh2en.append((v, k))
    zh2en.sort(key=lambda x: x[0])  # UTF-8 byte order

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by tools/build_dict.py. DO NOT EDIT.\n")
        f.write("// Edit dict/sample.csv instead, then re-run the script.\n\n")
        f.write("#ifndef MICROPY_INCLUDED_TRANSLATE_DICT_DATA_H\n")
        f.write("#define MICROPY_INCLUDED_TRANSLATE_DICT_DATA_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("typedef struct {\n")
        f.write("    const char *key;\n")
        f.write("    const char *value;\n")
        f.write("} tr_entry_t;\n\n")

        f.write(f"#define TR_EN2ZH_COUNT {len(en2zh)}\n")
        f.write("static const tr_entry_t tr_en2zh[TR_EN2ZH_COUNT] = {\n")
        for k, v in en2zh:
            f.write(f'    {{"{c_escape(k)}", "{c_escape(v)}"}},\n')
        f.write("};\n\n")

        f.write(f"#define TR_ZH2EN_COUNT {len(zh2en)}\n")
        f.write("static const tr_entry_t tr_zh2en[TR_ZH2EN_COUNT] = {\n")
        for k, v in zh2en:
            f.write(f'    {{"{c_escape(k)}", "{c_escape(v)}"}},\n')
        f.write("};\n\n")

        f.write("#endif // MICROPY_INCLUDED_TRANSLATE_DICT_DATA_H\n")

    print(f"Generated {out_path}")
    print(f"  en->zh: {len(en2zh)} entries")
    print(f"  zh->en: {len(zh2en)} entries")


if __name__ == "__main__":
    main()
